swagger: '2.0'
info:
  version: '1.0'
  title: Ratio Microservice API
host: 'localhost:3000'
basePath: /
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /rate-to-usd:
    x-swagger-router-controller: index
    get:
      description: Retrieve a array of ratioMicroservice documents
      operationId: ratioMicroserviceRetriveAll
      parameters:
        - name: page
          in: query
          type: integer
          description: Page number to get the next set of documents
        - name: count
          in: query
          type: integer
          description: Number of documents in each request
        - name: filter
          in: query
          type: string
          description: Filter documents based on certain fields
        - name: select
          in: query
          type: string
          description: Select fields to be displayed in documents
        - name: sort
          in: query
          type: string
          description: Sort documents based on field
        - name: countOnly
          in: query
          type: boolean
          description: Show only total count of records
      responses:
        '200':
          description: Array of ratioMicroservice documents
        '400':
          description: Bad parameters
        '500':
          description: Internal server error
    post:
      description: Create a new ratioMicroservice document
      operationId: ratioMicroserviceCreate
      parameters:
        - name: data
          in: body
          description: Payload to create a ratioMicroservice document
          schema:
            $ref: '#/definitions/ratioMicroservice_create'
      responses:
        '200':
          description: ratioMicroservice document with generated ID
        '400':
          description: Bad parameters
        '500':
          description: Internal server error
  '/rate-to-usd/{id}':
    x-swagger-router-controller: index
    get:
      description: Retrieve a single record of ratioMicroservice
      operationId: ratioMicroserviceRetrive
      parameters:
        - name: select
          in: query
          type: string
          description: Select fields to be displayed in document
        - name: id
          in: path
          type: string
          required: true
          description: Id of the document
      responses:
        '200':
          description: ratioMicroservice document for the ID
        '400':
          description: Bad parameters
        '404':
          description: No document found
        '500':
          description: Internal server error
    put:
      description: Update a ratioMicroservice document
      operationId: ratioMicroserviceUpdate
      parameters:
        - name: data
          in: body
          description: Payload to update a ratioMicroservice document
          schema:
            $ref: '#/definitions/ratioMicroservice_create'
        - name: id
          in: path
          type: string
          required: true
          description: Id of the ratioMicroservice document to be updated
      responses:
        '200':
          description: ratioMicroservice document after update
        '400':
          description: Bad parameters
        '404':
          description: No document found
        '500':
          description: Internal server error
    delete:
      description: Create a new ratioMicroservice
      operationId: ratioMicroserviceDelete
      parameters:
        - name: id
          in: path
          type: string
          required: true
          description: Id of the ratioMicroservice document to be deleted
      responses:
        '200':
          description: Deleted ratioMicroservice document
        '400':
          description: Bad parameters
        '404':
          description: No document found
        '500':
          description: Internal server error
definitions:
  ratioMicroservice_create:
    properties:
      code:
        type:
          - string
          - 'null'
      name:
        type:
          - string
          - 'null'
      rate:
        type:
          - number
          - 'null'
      bid:
        type:
          - number
          - 'null'
      ask:
        type:
          - number
          - 'null'
      stored:
        type:
          - string
          - 'null'
      lastRefreshed:
        type:
          - string
          - 'null'
